spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=hahaton;encrypt=true;trustServerCertificate=true
    username: server
    password: server
